#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# -----------------------------------------------------------------------------
# Program Name:           ncoda_osx.travis.yml
# Program Description:    Travis build config file for OS X build.
#
# Filename:               macOS/ncoda_osx.travis.yml
# Purpose:                This tells Travis how to execute the OS X build.
#
# Copyright (C) 2017 Jeff Treviño
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
# -----------------------------------------------------------------------------

env:
  global:
  - ENCRYPTION_LABEL: 50d7e6dd3298
  - COMMIT_AUTHOR_EMAIL: jeffrey.trevino@mgmail.com
  secure: "RN0ytrqxRp0YD0mZcP9InnP8gtO/mZl3mRoF+h0CM2I4a/3/dHxRPsxTYXNaHadxLqGmfd4JnnzkC5rRa5JySvjXi6aJzIDstYqNYtZyZTOQxWqO2tEQySqrVxDECeLC+FgIhbOQw4gNud1U3wYgL0UeTNQh73fSQpAhjBQOw1ygfYE8ZPk43RKqTNcQJwBxa7gPOfMO7x87aZS1n6aqlFVIYrG0sTiwm1qtCOT+Kq3BDuESBrxgKQhjx/ypDkYNv7qrcP+n+o+Fj8GrzCD2YtXJdnRs65osVTyUpvp5QsixfhEdM7O3Szc54zRPggeGLI2aWohqis6wi/DRngefXitlgz7uPe3w+Mkdjpa9wLVmFdQp1ncGqMHTSAIPw3NXdn++I0+MdYUJS6SQ19yG3GkuH2R6ubizbB3Js8X9r7q3Ki4WnX2pv3Y8ODDVS8D2JdlObAsIdR3aV8TBK7HnESviGOSlD3N+qiF7m6+T3TGYNgem8ejUVdI4McGO717XXVvPVEtii3sxHSZaXIQKfl2va8rSjZGYWesxiXGFMytn6AVVooMWye7sM5ySKbCwZlAYdWe3NeetTHtPon0zKNzu6KarG/985ZxwcEyfhl7J9YulhV55Wf4tg/0esHa4fqwXaQFw/HeZUzpLT8t6dwES7V5a4EVKQdAHxk6Hj3I="

notifications: # set notification options
  # disable all email
  email: false

matrix:
    include:
        - os: osx
          language: generic

# run
branches:
  only:
    - main

before_install:
  - source add-key.sh
  - git clone --recursive https://github.com/nCoda/julius.git julius
  - git clone https://github.com/nCoda/lychee.git lychee
  - git clone https://github.com/nCoda/fujian.git fujian
  - git clone https://github.com/nCoda/mercurial-hug.git mercurial-hug
  - rm julius/js/electron_main.js
  - cp electron_main_production.js julius/js/electron_main.js
  # might need this...
  # - brew link --overwrite node


install:
  - cd julius && npm install
  - cd ..
  - virtualenv ncoda_venv
  - source ncoda_venv/bin/activate
  - cd mercurial-hug && pip install . && cd ..
  - cd lychee && pip install . && cd ..
  - cd fujian && pip install . && cd ..
  # get dmgbuild to automate the dmg packaging
  - pip install dmgbuild
  # get mock and pytest to run the tests
  - pip install pytest
  - pip install mock
  # Use Browserify to compile the JS. And use LESS to compile the CSS.
  - cd julius && node_modules/.bin/browserify js/ncoda-init.js --outfile js/ncoda-compiled.js && cd ..
  - cd julius && node_modules/.bin/lessc css/ncoda/main.less css/ncoda/ main.css && cd ..

script: source build_test.sh

after_success:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=build-$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI build $TRAVIS_BUILD_NUMBER"
  - git push origin $GIT_TAG

before_deploy:
  - python package_ncoda_macOS.py

deploy:
  provider: releases
  api_key: DEPLOY_TOKEN
  file: nCoda.dmg
  skip_cleanup: true
  on:
    tags: false