env:
  global:
    secure: "LVAu6qNHZoyJEyctOJEmqraxdvn7oirPOV1V1U0Q2RDPAb/dYZNj7ta3ULPtsUCsBsJLSjVr4RHg0S8r3LqAD1miqIdGLyT++FYXZTfXChYTHn2sxLv8Zmdra8VFQRG/0ZHORltCcDAp1uk6DSph14TQABk/cXcqZQGJbKsDlkhk7r/yxJvbVWKZ0MdCgxwF5xYkQJFiyV7KUpmoOb4wOd8W3kFA4EiBgwrKKZOUetdo4fDXTx4A2NnFYp1Qz4Kl7VyqGOyR4PXwUn0X/DY2R2TU1kmu6v5ZiHesyEw11QZi2NJi2uKghKzYrlE4DDcj0Leid6GoOmA0Ptai2uTeBdZprUwM/GTj5g/0qp0l5H5fcURnIUejLfucVMA0jHGwBDodrWtuUJIuK4BR/3Bq7wuGRgabFaoSj7f8a2DGwT9oMdNYmetg3121ts74/t0wemCqz/z04aEe0KWVgDsuGI7QqDcgTsWx9ZWZJ8fBZErZrZZYIZz0i6LWWojn+qnfx448x83jKjn7IxPNj/Ep+Az/BztICteQS31lW+m/VhvW5f0aPbc8Jk8Lou2ZydDsYAOmKY6UGtGXpDJ1epbQzqaOqXXM9Qn9B266oTYgxZmcmmHJ+f56/Y9jYu57ecR3iJp+zNB7Ho5MnM2FYtN89Gvzg5wMowEwz0HKY9MUpIA="

notifications:
  email: false
matrix:
  include:
  - os: osx
    language: generic
branches:
  only:
  - main
before_install:
- git clone --recursive https://github.com/nCoda/julius.git julius
- git clone https://github.com/nCoda/lychee.git lychee
- git clone https://github.com/nCoda/fujian.git fujian
- git clone https://github.com/nCoda/mercurial-hug.git mercurial-hug
- rm julius/js/electron_main.js
- cp electron_main_production.js julius/js/electron_main.js
install:
- cd julius && npm install
- cd ..
- virtualenv ncoda_venv
- source ncoda_venv/bin/activate
- cd mercurial-hug && pip install . && cd ..
- cd lychee && pip install . && cd ..
- cd fujian && pip install . && cd ..
- pip install dmgbuild
- pip install pytest
- pip install mock
- cd julius && node_modules/.bin/browserify js/ncoda-init.js --outfile js/ncoda-compiled.js
  && cd ..
- cd julius && node_modules/.bin/lessc css/ncoda/main.less css/ncoda/ main.css &&
  cd ..
script: source build_test.sh

before_deploy:
- python package_ncoda_macOS.py

deploy:
  - source deploy.sh
  # provider: releases
  # file: nCoda.dmg
  # skip_cleanup: true
  # on:
  #   tags: false
